### ISSUE TITLE
ImportError: cannot import name 'APIKEY' from 'config'

### ISSUE THREAD

**Issue by Liaoshihua** [WithHades/banfoStyle#1]
when I use `python main.py`, `ImportError: cannot import name 'APIKEY' from 'config'`

**Comment by Julianexia** [comment]
me，too

**Comment by WithHades** [comment]
> when I use `python main.py`, `ImportError: cannot import name 'APIKEY' from 'config'`

这个是用来翻译用的，当前版本用不到这个key，可以自己新建一个config文件，任意设置一个值

**Comment by WithHades** [comment]
> me，too

这个是用来翻译用的，当前版本用不到这个key，可以自己新建一个config文件，任意设置一个值
